---
# tasks file for glusterfs-ansible-role

- name: Remove volume(s)
  gluster_volume:
    name: "{{ item.volume }}"
    state: absent
  delegate_to: "{{ glusterfs_nodes[0] }}"
  run_once: True
  with_items: "{{ glusterfs_volumes }}"
  when: >
    (item.state is defined and item.state == 'absent') and
    item.volume in glusterfs_volume_list.stdout

- name: Delete removed volume(s) bricks directories (1/2)
  file:
    name: "{{ glusterfs_default_bricks_dir }}/{{ item[0].volume }}"
    state: absent
  delegate_to: "{{ item[1] }}"
  with_nested: 
    - "{{ glusterfs_volumes }}"
    - "{{ glusterfs_nodes }}"
  when: >
    glusterfs_delete_bricks_dir_after_removal and
    (item[0].state is defined and item[0].state == 'absent') and
    (item[0].nodes is undefined or item[1] in item[0].nodes) and
    item[0].bricks is undefined

- name: Delete removed volume(s) bricks directories (2/2)
  file:
    name: "{{ item.1 }}"
    state: absent
  with_subelements:
    - "{{ glusterfs_volumes }}"
    - bricks
    - skip_missing: True
  when: >
    glusterfs_delete_bricks_dir_after_removal and
    (item.0.state is defined and item.0.state == 'absent')
