---
# tasks file for glusterfs-ansible-role

- name: Unmount volume(s)
  mount:
    name: "{{ item.mount.path }}"
    src: "{% if item.nodes is defined %}{{ item.nodes[0] + ':/' + item.volume }}{% else %}{{ glusterfs_nodes[0] + ':/' + item.volume }}{% endif %}"
    fstype: glusterfs
    opts: "{%- if item.mount.options is defined -%}{{ item.mount.options }}{%- else -%}{%- if item.nodes is defined and item.nodes | length > 1 -%}{{ 'defaults,_netdev,backupvolfile-server=' + item.nodes[1] }}{%- elif glusterfs_nodes | length > 1 -%}{{ 'defaults,_netdev,backupvolfile-server=' + glusterfs_nodes[1] }}{%- else -%}'defaults,_netdev'{%- endif -%}{%- endif -%}"
    state: unmounted
  with_items: "{{ glusterfs_volumes }}"
  when: >
    item.mount is defined and
    (item.state is defined and item.state == 'absent')

- name: Remove mount(s) from fstab
  mount:
    name: "{{ item.mount.path }}"
    src: "{% if item.nodes is defined %}{{ item.nodes[0] + ':/' + item.volume }}{% else %}{{ glusterfs_nodes[0] + ':/' + item.volume }}{% endif %}"
    fstype: glusterfs
    opts: "{%- if item.mount.options is defined -%}{{ item.mount.options }}{%- else -%}{%- if item.nodes is defined and item.nodes | length > 1 -%}{{ 'defaults,_netdev,backupvolfile-server=' + item.nodes[1] }}{%- elif glusterfs_nodes | length > 1 -%}{{ 'defaults,_netdev,backupvolfile-server=' + glusterfs_nodes[1] }}{%- else -%}'defaults,_netdev'{%- endif -%}{%- endif -%}"
    state: absent
  with_items: "{{ glusterfs_volumes }}"
  when: >
    item.mount is defined and
    (item.state is defined and item.state == 'absent')
